name: Check Uptime

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Ping sharpennd.xyz
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://sharpennd.xyz)
          if [ "$STATUS" -ne 200 ]; then
            echo "Server down on $(date)" >> downtime.log
          else
            echo "Up on $(date)" >> uptime.log
          fi

      - name: Commit result
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add downtime.log uptime.log
          git commit -m "Update uptime log [skip ci]" || echo "No changes"
          git push
